import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { IInstitute } from '../models/Institute';
import { amountInWords } from './receiptPdf';

type StudentLite = {
  firstName?: string;
  lastName?: string;
  admissionNo?: string;
  phone?: string;
  email?: string;
  address?: string;
  className?: string;
  sectionName?: string;
  sessionName?: string;
};

export type PaymentLine = {
  receiptNo: string;
  amount: number;
  paidAt: Date | string;
  method?: string;
  invoiceNo?: string;
  billingMonth?: string;
  categorySummary?: string;
};

const BRAND = '#0f5c4c';
const BRAND_LIGHT = '#e8f3ef';
const INK = '#1a1a1a';
const MUTED = '#5c6675';
const LINE = '#d0d5dd';

function money(n: number, currency = 'INR') {
  try {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency,
      maximumFractionDigits: 2,
    }).format(n);
  } catch {
    return `₹${n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }
}

function fmtDate(d?: Date | string | null) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

function fmtMonth(month: string) {
  if (!/^\d{4}-\d{2}$/.test(month)) return month;
  const [y, m] = month.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, 1)).toLocaleDateString('en-IN', {
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  });
}

function drawHLine(doc: PDFKit.PDFDocument, x1: number, x2: number, y: number, color = LINE) {
  doc.save().strokeColor(color).lineWidth(0.8).moveTo(x1, y).lineTo(x2, y).stroke().restore();
}

function drawRect(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  w: number,
  h: number,
  fill?: string,
  stroke = LINE
) {
  doc.save();
  if (fill) doc.fillColor(fill).rect(x, y, w, h).fill();
  doc.strokeColor(stroke).lineWidth(0.8).rect(x, y, w, h).stroke();
  doc.restore();
}

/** Indian FY: Apr–Mar. Returns label + date bounds (UTC dates). */
export function indianFinancialYear(asOf = new Date()) {
  const y = asOf.getFullYear();
  const m = asOf.getMonth(); // 0-based
  const startYear = m >= 3 ? y : y - 1;
  const label = `${startYear}-${String(startYear + 1).slice(-2)}`;
  const start = new Date(Date.UTC(startYear, 3, 1, 0, 0, 0));
  const endExclusive = new Date(Date.UTC(startYear + 1, 3, 1, 0, 0, 0));
  return { label, startYear, start, endExclusive };
}

function pipePdf(
  res: Response,
  filename: string,
  inline: boolean,
  title: string,
  institute: IInstitute,
  build: (doc: PDFKit.PDFDocument, ctx: { left: number; right: number; contentW: number; pageW: number }) => void
) {
  const pageMargin = 40;
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: pageMargin, bottom: pageMargin, left: pageMargin, right: pageMargin },
    info: { Title: title, Author: institute.name },
  });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `${inline ? 'inline' : 'attachment'}; filename="${filename}"`
  );
  doc.pipe(res);

  const pageW = doc.page.width;
  const contentW = pageW - pageMargin * 2;
  const left = pageMargin;
  const right = pageW - pageMargin;

  doc.save().fillColor(BRAND).rect(0, 0, pageW, 8).fill().restore();
  build(doc, { left, right, contentW, pageW });

  const footerY = doc.page.height - 28;
  doc.save().fillColor(BRAND).rect(0, footerY, pageW, 28).fill().restore();
  doc
    .fillColor('#fff')
    .font('Helvetica')
    .fontSize(7)
    .text(
      `${institute.name}  ·  Generated by AnyIT Institute CMS  ·  ${fmtDate(new Date())}`,
      left,
      footerY + 10,
      { width: contentW, align: 'center' }
    );

  doc.end();
}

function writeStudentHeader(
  doc: PDFKit.PDFDocument,
  institute: IInstitute,
  student: StudentLite | null,
  badgeTitle: string,
  badgeSub: string,
  ctx: { left: number; right: number; contentW: number }
) {
  const { left, right, contentW } = ctx;
  let y = 40;

  doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(18).text(institute.name, left, y, {
    width: contentW * 0.58,
  });
  doc
    .fillColor(MUTED)
    .font('Helvetica')
    .fontSize(8)
    .text(`Institute Code: ${institute.code}`, left, y + 24);

  const badgeX = left + contentW * 0.58;
  drawRect(doc, badgeX, y, contentW * 0.42, 42, BRAND_LIGHT, BRAND);
  doc
    .fillColor(BRAND)
    .font('Helvetica-Bold')
    .fontSize(11)
    .text(badgeTitle, badgeX, y + 8, { width: contentW * 0.42, align: 'center' });
  doc
    .fillColor(MUTED)
    .font('Helvetica')
    .fontSize(8)
    .text(badgeSub, badgeX, y + 24, { width: contentW * 0.42, align: 'center' });

  y += 52;
  const addressBits = [institute.address, institute.phone, institute.email].filter(Boolean);
  if (addressBits.length) {
    doc
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(9)
      .text(addressBits.join('  ·  '), left, y, { width: contentW });
    y += 16;
  }

  drawHLine(doc, left, right, y);
  y += 12;

  const studentName = student
    ? `${student.firstName || ''} ${student.lastName || ''}`.trim() || 'Student'
    : 'Student';
  drawRect(doc, left, y, contentW, 70, '#fafafa');
  doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(9).text('STUDENT', left + 10, y + 8);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(12).text(studentName, left + 10, y + 24);
  doc.fillColor(MUTED).font('Helvetica').fontSize(9);
  const meta = [
    student?.admissionNo ? `Admission: ${student.admissionNo}` : null,
    student?.className
      ? `Class: ${student.className}${student.sectionName ? `-${student.sectionName}` : ''}`
      : null,
    student?.sessionName ? `Session: ${student.sessionName}` : null,
    student?.phone ? `Phone: ${student.phone}` : null,
  ]
    .filter(Boolean)
    .join('   ·   ');
  doc.text(meta, left + 10, y + 42, { width: contentW - 20 });
  y += 84;
  return y;
}

/** Month-wise fee receipt (when some amount paid for that billing month). */
export async function streamMonthFeeReceiptPdf(
  res: Response,
  opts: {
    institute: IInstitute;
    student: StudentLite | null;
    month: string;
    payments: PaymentLine[];
    billedTotal: number;
    paidTotal: number;
    pendingTotal: number;
    inline?: boolean;
  }
) {
  const {
    institute,
    student,
    month,
    payments,
    billedTotal,
    paidTotal,
    pendingTotal,
    inline = false,
  } = opts;
  const currency = institute.settings?.currency || 'INR';
  const filename = `fee-month-${student?.admissionNo || 'student'}-${month}.pdf`;

  pipePdf(res, filename, inline, `Month Fee Receipt ${month}`, institute, (doc, ctx) => {
    const { left, right, contentW } = ctx;
    let y = writeStudentHeader(
      doc,
      institute,
      student,
      'MONTH FEE RECEIPT',
      fmtMonth(month),
      ctx
    );

    doc
      .fillColor(INK)
      .font('Helvetica')
      .fontSize(10)
      .text(
        `This receipt summarizes fees paid for billing month ${fmtMonth(month)}.`,
        left,
        y,
        { width: contentW }
      );
    y += 20;

    // Summary cards
    const cardW = (contentW - 16) / 3;
    const cards = [
      { label: 'Billed', value: money(billedTotal, currency) },
      { label: 'Paid', value: money(paidTotal, currency) },
      { label: 'Pending', value: money(pendingTotal, currency) },
    ];
    cards.forEach((c, i) => {
      const x = left + i * (cardW + 8);
      drawRect(doc, x, y, cardW, 44, BRAND_LIGHT, BRAND);
      doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(c.label, x + 8, y + 8);
      doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(12).text(c.value, x + 8, y + 22);
    });
    y += 56;

    doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(10).text('Payment details', left, y);
    y += 16;

    // Table header
    drawRect(doc, left, y, contentW, 22, BRAND);
    doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8);
    doc.text('Date', left + 6, y + 7, { width: 70 });
    doc.text('Receipt', left + 76, y + 7, { width: 90 });
    doc.text('Invoice', left + 166, y + 7, { width: 90 });
    doc.text('Mode', left + 256, y + 7, { width: 60 });
    doc.text('Amount', left + 320, y + 7, { width: contentW - 326, align: 'right' });
    y += 22;

    doc.font('Helvetica').fontSize(8).fillColor(INK);
    for (const [idx, p] of payments.entries()) {
      if (y > doc.page.height - 120) {
        doc.addPage();
        y = 40;
      }
      if (idx % 2 === 0) drawRect(doc, left, y, contentW, 20, '#f7faf9', '#f7faf9');
      doc.fillColor(INK);
      doc.text(fmtDate(p.paidAt), left + 6, y + 6, { width: 70 });
      doc.text(p.receiptNo, left + 76, y + 6, { width: 90 });
      doc.text(p.invoiceNo || '—', left + 166, y + 6, { width: 90 });
      doc.text((p.method || '—').toUpperCase(), left + 256, y + 6, { width: 60 });
      doc.text(money(p.amount, currency), left + 320, y + 6, {
        width: contentW - 326,
        align: 'right',
      });
      y += 20;
    }

    y += 10;
    drawHLine(doc, left, right, y);
    y += 12;
    doc
      .fillColor(INK)
      .font('Helvetica-Bold')
      .fontSize(10)
      .text(`Total paid: ${money(paidTotal, currency)}`, left, y, { align: 'right', width: contentW });
    y += 16;
    doc
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(9)
      .text(`Amount in words: ${amountInWords(paidTotal)}`, left, y, { width: contentW });
    y += 24;
    doc
      .fillColor(MUTED)
      .fontSize(8)
      .text(
        'Computer-generated month receipt. Retain for fee records. For individual payment invoices use the payment receipt.',
        left,
        y,
        { width: contentW }
      );
  });
}

/** FY fee payment statement till today — useful for ITR fee / education expense filling. */
export async function streamItrFeeStatementPdf(
  res: Response,
  opts: {
    institute: IInstitute;
    student: StudentLite | null;
    fyLabel: string;
    fyStart: Date;
    asOf: Date;
    payments: PaymentLine[];
    inline?: boolean;
  }
) {
  const { institute, student, fyLabel, fyStart, asOf, payments, inline = false } = opts;
  const currency = institute.settings?.currency || 'INR';
  const totalPaid = payments.reduce((s, p) => s + p.amount, 0);
  const filename = `fee-ITR-${student?.admissionNo || 'student'}-FY${fyLabel}-till-${fmtDate(asOf).replace(/\s/g, '')}.pdf`;

  pipePdf(
    res,
    filename,
    inline,
    `Fee Payment Statement FY ${fyLabel}`,
    institute,
    (doc, ctx) => {
      const { left, right, contentW } = ctx;
      let y = writeStudentHeader(
        doc,
        institute,
        student,
        'FEE STATEMENT (ITR)',
        `FY ${fyLabel}`,
        ctx
      );

      drawRect(doc, left, y, contentW, 54, '#fff8f0', '#e09f3e');
      doc
        .fillColor('#8a4b12')
        .font('Helvetica-Bold')
        .fontSize(9)
        .text('For Income Tax Return (ITR) reference', left + 10, y + 8);
      doc
        .fillColor(MUTED)
        .font('Helvetica')
        .fontSize(8)
        .text(
          `Payments received from ${fmtDate(fyStart)} to ${fmtDate(asOf)} (same financial year, till today). Use total paid while filling education / tuition related fields as applicable under current tax rules. This is not tax advice.`,
          left + 10,
          y + 22,
          { width: contentW - 20 }
        );
      y += 66;

      const cardW = (contentW - 8) / 2;
      drawRect(doc, left, y, cardW, 48, BRAND_LIGHT, BRAND);
      drawRect(doc, left + cardW + 8, y, cardW, 48, BRAND_LIGHT, BRAND);
      doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('Financial year', left + 10, y + 8);
      doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(14).text(`FY ${fyLabel}`, left + 10, y + 24);
      doc
        .fillColor(MUTED)
        .font('Helvetica')
        .fontSize(8)
        .text('Total paid (till today)', left + cardW + 18, y + 8);
      doc
        .fillColor(BRAND)
        .font('Helvetica-Bold')
        .fontSize(14)
        .text(money(totalPaid, currency), left + cardW + 18, y + 24);
      y += 60;

      doc
        .fillColor(INK)
        .font('Helvetica-Bold')
        .fontSize(10)
        .text(`Payment register (${payments.length})`, left, y);
      y += 14;

      drawRect(doc, left, y, contentW, 22, BRAND);
      doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8);
      doc.text('#', left + 6, y + 7, { width: 18 });
      doc.text('Paid on', left + 24, y + 7, { width: 70 });
      doc.text('Receipt', left + 94, y + 7, { width: 85 });
      doc.text('Invoice / Month', left + 179, y + 7, { width: 120 });
      doc.text('Mode', left + 300, y + 7, { width: 50 });
      doc.text('Amount', left + 350, y + 7, { width: contentW - 356, align: 'right' });
      y += 22;

      doc.font('Helvetica').fontSize(8);
      for (const [idx, p] of payments.entries()) {
        if (y > doc.page.height - 110) {
          doc.addPage();
          y = 40;
          drawRect(doc, left, y, contentW, 22, BRAND);
          doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8);
          doc.text('#', left + 6, y + 7, { width: 18 });
          doc.text('Paid on', left + 24, y + 7, { width: 70 });
          doc.text('Receipt', left + 94, y + 7, { width: 85 });
          doc.text('Invoice / Month', left + 179, y + 7, { width: 120 });
          doc.text('Mode', left + 300, y + 7, { width: 50 });
          doc.text('Amount', left + 350, y + 7, { width: contentW - 356, align: 'right' });
          y += 22;
          doc.font('Helvetica').fontSize(8);
        }
        if (idx % 2 === 0) drawRect(doc, left, y, contentW, 20, '#f7faf9', '#f7faf9');
        doc.fillColor(INK);
        doc.text(String(idx + 1), left + 6, y + 6, { width: 18 });
        doc.text(fmtDate(p.paidAt), left + 24, y + 6, { width: 70 });
        doc.text(p.receiptNo, left + 94, y + 6, { width: 85 });
        doc.text(
          [p.invoiceNo, p.billingMonth ? fmtMonth(p.billingMonth) : null].filter(Boolean).join(' / ') ||
            '—',
          left + 179,
          y + 6,
          { width: 120 }
        );
        doc.text((p.method || '—').toUpperCase(), left + 300, y + 6, { width: 50 });
        doc.text(money(p.amount, currency), left + 350, y + 6, {
          width: contentW - 356,
          align: 'right',
        });
        y += 20;
      }

      y += 12;
      drawHLine(doc, left, right, y);
      y += 12;
      doc
        .fillColor(INK)
        .font('Helvetica-Bold')
        .fontSize(11)
        .text(`Grand total paid in FY ${fyLabel} (till ${fmtDate(asOf)}): ${money(totalPaid, currency)}`, left, y, {
          width: contentW,
        });
      y += 16;
      doc
        .fillColor(MUTED)
        .font('Helvetica')
        .fontSize(9)
        .text(`Amount in words: ${amountInWords(totalPaid)}`, left, y, { width: contentW });
      y += 22;
      doc
        .fillColor(MUTED)
        .fontSize(8)
        .text(
          'Declaration: This statement lists fee payments recorded in the institute CMS for the student during the selected financial year up to the generation date. Verify against bank statements before ITR filing.',
          left,
          y,
          { width: contentW }
        );
    }
  );
}
